name: Add an entry
description: Add an entry to the Sapphire index.
labels: []
body: 
  - type: markdown
    attributes:
      value: "## Sapphire index entry"
  - type: input
    id: entry
    attributes:
      label: Your mod link
      description: Add a link to your .sapphire file which can be downloaded directly.
      placeholder: "https://github.com/<user>/<repo>/releases/download/<tag>/<mod>.sapphire"
    validations:
      required: true
